name: Deploy
run-name: ${{ github.actor }} initiated a deployment
on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t ${{ vars.SPRING_APP_IMAGE_NAME }}:latest .

      - name: Save Docker image as tar file
        run: docker save -o ${{ vars.SPRING_APP_IMAGE_NAME }}.tar ${{ vars.SPRING_APP_IMAGE_NAME }}:latest

      - name: Transfer Docker image to remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_SERVER_USERNAME }}@${{ vars.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          mkdir -p ${{ vars.REMOTE_SERVER_PATH }}
          ENDSSH
          scp -o StrictHostKeyChecking=no ${{ vars.SPRING_APP_IMAGE_NAME }}.tar ${{ vars.REMOTE_SERVER_USERNAME }}@${{ vars.REMOTE_SERVER_ADDRESS }}:${{ vars.REMOTE_SERVER_PATH }}

      - name: Load Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_SERVER_USERNAME }}@${{ vars.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          docker load -i ${{ vars.REMOTE_SERVER_PATH }}/${{ vars.SPRING_APP_IMAGE_NAME }}.tar
          ENDSSH

      - name: Transfer Docker Compose remote server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ vars.REMOTE_SERVER_USERNAME }}@${{ vars.REMOTE_SERVER_ADDRESS }}:${{ vars.REMOTE_SERVER_PATH }}
          ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_SERVER_USERNAME }}@${{ vars.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'

      - name: Deploy Docker containers using Docker Compose on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ vars.REMOTE_SERVER_USERNAME }}@${{ vars.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
          docker compose -f ${{ vars.REMOTE_SERVER_PATH }}/docker-compose.yml down
          docker compose -f ${{ vars.REMOTE_SERVER_PATH }}/docker-compose.yml up -d
          docker image prune -f
          ENDSSH